[project]
name = "calculator-mcp-rubens"
keywords = ["ai", "calculator", "math", "llm", "mcp", "utility"]
version = "0.0.2"
description = "A calculator MCP server"
authors = [
    { name = "Rubens Gomes", email = "rubens.s.gomes@gmail.com" }
]
readme = "README.md"
license = "MIT"
requires-python = ">=3.14.0,<4.0.0"
classifiers = [
    "Programming Language :: Python :: 3"
]
dependencies = [
    "fastmcp (>=4.0.4,<5.0.0)",
    "pyyaml (>=6.0.3,<7.0.0)",
    "calculator-lib-rubens (>=0.2.0,<2.0.0)",
    "py-key-value-aio[disk] (>=0.1.4,<1.0.0)",
]

[project.scripts]
calculator-mcp = "calculator_mcp.main:main"

[project.urls]
Homepage = "https://github.com/rubensgomes-org/calculator-mcp"
Documentation = "https://github.com/rubensgomes-org/calculator-mcp/blob/main/README.md"
Repository = "https://github.com/rubensgomes-org/calculator-mcp"

[tool.poetry]
packages = [{ include = "calculator_mcp", from = "src" }]

[build-system]
requires = ["poetry-core>=2.4.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.run]
source = ["calculator_mcp"]
branch = true

[tool.coverage.report]
show_missing = true
fail_under = 90

[dependency-groups]
dev = [
    # see more executable packages in the project documentation
    "black (>=26.5.1,<27.0.0)",
    "httpx2 (>=2.12.0,<3.0.0)",
    "isort (>=9.0.1,<10.0.0)",
    "mypy (>=1.20.2,<2.0.0)",
    "poethepoet (>=0.48.0,<1.0.0)",
    "poetry (>=2.4.3,<3.0.0)",
    "pylint (>=4.0.8,<5.0.0)",
    "types-pyyaml (>=6.0.12.2,<7.0.0.0)",
    "uv (>=0.12.15,<1.0.0)",
]
test = [
    "coverage (>=7.16.0,<8.0.0)",
    "pytest (>=9.1.1,<10.0.0)",
    "pytest-asyncio (>=1.4.0,<2.0.0)",
    "pytest-cov (>=7.1.0,<8.0.0)",
]

[tool.black]
line-length = 80

[tool.isort]
line_length = 80
profile = "black"

[tool.mypy]
mypy_path = "src"
ignore_missing_imports = true

[tool.pytest.ini_options]
asyncio_mode = "auto"

[tool.poe.tasks]
# Poe the Poetry "poethepoet" task runner needs to be installed.
# Define individual cleanup tasks
_clean_cache = "poetry cache clear --all"
_clean_misc = "rm -rf  .mypy_cache dist build"
_clean_pyc = "find . -name '*.pyc' -delete"
_clean_pycache = "find . -name '__pycache__' -type d -exec rm -rf {} +"
_clean_pytest = "rm -rf .pytest_cache"
_clean_venv = "poetry env remove --all"
# Combine them into one 'clean' command.  Similar to `make clean`
# `poetry run poe clean` OR
# `poe clean`
[tool.poe.tasks.clean]
sequence = [
    "_clean_cache",
    "_clean_misc",
    "_clean_pyc",
    "_clean_pycache",
    "_clean_pytest",
    "_clean_venv",
]
help = "Remove all project artifacts"
